#TWITTER API

USER_KEY = "rX0n8E8AsfbXkOQXyWIZIGDYq"
USER_SECRET = "vuxpSPVy5xDLaM3fkCqs1fK10Ldaw1LumywNPYdzDLkf9oasfC"
USER_TOKEN = "500420636-kZHWR2CJAYAGKGuXNyrBKKDRtEXFqio0rJDSZ6Xj"
USER_TOKEN_SECRET = "BojXlL7UKaMAyvcyO87tsjTnEG7OppphvZVMXmcbpBDph"
CONSUMER_KEY = "P6F9glaUd7uB3kj5ElRWRXIDm"
CONSUMER_SECRET = "lasmKKLlE0WzOXTe61u1s1PERsuKludoUIkY9W2XWkHf6xxbsW"
ACCESS_TOKEN = "2832004285-wvzniXfCRDi3YyiXa8fTxPcHUNscIAWj5TtNtPo"
ACCESS_TOKEN_SECRET = "6lcArRNPYPxruE0BGCpqlHwLSq3DN4QCw9F1fluT1uO68"

#GNIP API

GNIP_USERNAME="pernghwa@media.mit.edu"
GNIP_PASSWORD="2oaugidr"

#FLASK USER
FLASK_USER="paukung"
FLASK_PASS="temp"
